// Generated by nativescript-preferences from preferences.json. Do not edit; edit preferences.json instead.
import { Preferences } from 'nativescript-preferences';

export interface DemoSettings {
	name_preference: string;
	enabled_preference: boolean;
	theme_preference: 'system' | 'light' | 'dark';
	volume_preference: number;
	analytics_preference: boolean;
}

export const settingsDefaults: Readonly<DemoSettings> = {
	name_preference: '',
	enabled_preference: true,
	theme_preference: 'system',
	volume_preference: 50,
	analytics_preference: false,
};

/** One typed instance for the whole app, backed by the store the OS settings UI edits. */
export const settings = new Preferences<DemoSettings>({ defaults: settingsDefaults });
