'use strict';

/**
 * Turns one `preferences.json` into the platform files the OS settings UIs need, plus a typed
 * TypeScript module for the app. Pure Node, no NativeScript dependency, so it runs from the CLI
 * hook and from the `ns-preferences` binary alike.
 */

const fs = require('fs');
const path = require('path');

const GENERATED_MARKER = 'Generated by nativescript-preferences';
const ITEM_TYPES = ['group', 'screen', 'text', 'toggle', 'list', 'multilist', 'slider', 'label'];
const KEY_PATTERN = /^[A-Za-z_][A-Za-z0-9_]*$/;
const DEFAULT_CONFIG_FILE = 'preferences.json';

const DEFAULT_OUTPUT = {
	ios: 'App_Resources/iOS/Settings.bundle',
	android: 'App_Resources/Android/src/main/res',
	androidResource: 'preferences',
	typescript: undefined,
	interfaceName: 'AppSettings',
	exportName: 'settings',
};

class PreferencesConfigError extends Error {
	constructor(message) {
		super(`preferences.json: ${message}`);
		this.name = 'PreferencesConfigError';
	}
}

// Loading & validation ---------------------------------------------------------------------------

function loadConfig(file) {
	let text;
	try {
		text = fs.readFileSync(file, 'utf8');
	} catch (error) {
		throw new PreferencesConfigError(`could not read ${file}: ${error.message}`);
	}
	let json;
	try {
		json = JSON.parse(text);
	} catch (error) {
		throw new PreferencesConfigError(`${file} is not valid JSON: ${error.message}`);
	}
	return normalizeConfig(json);
}

function normalizeConfig(json) {
	if (!json || typeof json !== 'object' || Array.isArray(json)) {
		throw new PreferencesConfigError('the root must be an object with an "items" array.');
	}
	if (!Array.isArray(json.items)) {
		throw new PreferencesConfigError('"items" must be an array.');
	}
	const output = Object.assign({}, DEFAULT_OUTPUT, json.output || {});
	for (const field of ['androidResource', 'interfaceName', 'exportName']) {
		if (typeof output[field] !== 'string' || !output[field]) {
			throw new PreferencesConfigError(`"output.${field}" must be a non-empty string.`);
		}
	}
	// `false` switches an output off entirely, for people who maintain that file by hand.
	for (const field of ['ios', 'android']) {
		if (output[field] !== false && (typeof output[field] !== 'string' || !output[field])) {
			throw new PreferencesConfigError(`"output.${field}" must be a path or false.`);
		}
	}
	if (output.typescript !== undefined && output.typescript !== false && (typeof output.typescript !== 'string' || !output.typescript)) {
		throw new PreferencesConfigError('"output.typescript" must be a path or false when set.');
	}
	const seenKeys = new Map();
	const items = json.items.map((item, index) => normalizeItem(item, `items[${index}]`, seenKeys, 0));
	return { title: typeof json.title === 'string' ? json.title : 'Settings', output, items };
}

function normalizeItem(item, where, seenKeys, depth) {
	if (!item || typeof item !== 'object' || Array.isArray(item)) {
		throw new PreferencesConfigError(`${where} must be an object.`);
	}
	const type = item.type;
	if (!ITEM_TYPES.includes(type)) {
		throw new PreferencesConfigError(`${where}.type must be one of ${ITEM_TYPES.join(', ')}, got ${JSON.stringify(type)}.`);
	}
	const result = { type };
	for (const field of ['title', 'summary', 'placeholder']) {
		if (item[field] !== undefined) {
			if (typeof item[field] !== 'string') {
				throw new PreferencesConfigError(`${where}.${field} must be a string.`);
			}
			result[field] = item[field];
		}
	}

	for (const platform of ['ios', 'android']) {
		if (item[platform] !== undefined) {
			result[platform] = normalizeOverride(item[platform], `${where}.${platform}`, platform);
		}
	}

	if (type !== 'group') {
		if (typeof item.key !== 'string' || !KEY_PATTERN.test(item.key)) {
			throw new PreferencesConfigError(`${where}.key must match ${KEY_PATTERN} (letters, digits, underscore).`);
		}
		if (seenKeys.has(item.key)) {
			throw new PreferencesConfigError(`${where}.key "${item.key}" is already used by ${seenKeys.get(item.key)}.`);
		}
		seenKeys.set(item.key, where);
		result.key = item.key;
	}

	if (type === 'group' || type === 'screen') {
		if (!Array.isArray(item.items)) {
			throw new PreferencesConfigError(`${where}.items must be an array.`);
		}
		if (type === 'screen' && !result.title) {
			throw new PreferencesConfigError(`${where}.title is required for a screen.`);
		}
		result.items = item.items.map((child, index) => {
			const childWhere = `${where}.items[${index}]`;
			if (type === 'group' && (child && child.type === 'group')) {
				throw new PreferencesConfigError(`${childWhere}: a group cannot contain another group. Use a screen for nesting.`);
			}
			return normalizeItem(child, childWhere, seenKeys, depth + 1);
		});
		return result;
	}

	switch (type) {
		case 'text':
			result.default = expect(item, 'default', where, 'string', '');
			if (item.secure !== undefined) {
				result.secure = expect(item, 'secure', where, 'boolean');
			}
			if (item.keyboard !== undefined) {
				const keyboards = ['default', 'email', 'number', 'decimal', 'phone', 'url'];
				if (!keyboards.includes(item.keyboard)) {
					throw new PreferencesConfigError(`${where}.keyboard must be one of ${keyboards.join(', ')}.`);
				}
				result.keyboard = item.keyboard;
			}
			if (item.autocapitalize !== undefined) {
				const modes = ['none', 'sentences', 'words', 'characters'];
				if (!modes.includes(item.autocapitalize)) {
					throw new PreferencesConfigError(`${where}.autocapitalize must be one of ${modes.join(', ')}.`);
				}
				result.autocapitalize = item.autocapitalize;
			}
			if (item.autocorrect !== undefined) {
				result.autocorrect = expect(item, 'autocorrect', where, 'boolean');
			}
			break;
		case 'toggle':
			result.default = expect(item, 'default', where, 'boolean', false);
			break;
		case 'list':
		case 'multilist': {
			result.options = normalizeOptions(item.options, where);
			const values = result.options.map((option) => option.value);
			if (type === 'list') {
				if (item.default !== undefined) {
					const value = expect(item, 'default', where, 'string');
					if (!values.includes(value)) {
						throw new PreferencesConfigError(`${where}.default "${value}" is not one of the option values.`);
					}
					result.default = value;
				}
			} else {
				const defaults = item.default === undefined ? [] : item.default;
				if (!Array.isArray(defaults) || defaults.some((value) => typeof value !== 'string')) {
					throw new PreferencesConfigError(`${where}.default must be an array of strings.`);
				}
				for (const value of defaults) {
					if (!values.includes(value)) {
						throw new PreferencesConfigError(`${where}.default contains "${value}", which is not one of the option values.`);
					}
				}
				result.default = defaults;
			}
			break;
		}
		case 'slider': {
			result.min = expect(item, 'min', where, 'number', 0);
			result.max = expect(item, 'max', where, 'number', 100);
			if (result.min >= result.max) {
				throw new PreferencesConfigError(`${where}.min must be less than max.`);
			}
			result.default = expect(item, 'default', where, 'number', result.min);
			if (result.default < result.min || result.default > result.max) {
				throw new PreferencesConfigError(`${where}.default must be between min and max.`);
			}
			if (item.step !== undefined) {
				result.step = expect(item, 'step', where, 'number');
				if (result.step <= 0) {
					throw new PreferencesConfigError(`${where}.step must be positive.`);
				}
			}
			for (const field of ['min', 'max', 'default', 'step']) {
				if (result[field] !== undefined && !Number.isInteger(result[field])) {
					throw new PreferencesConfigError(`${where}.${field} must be an integer; Android SeekBarPreference stores integers.`);
				}
			}
			break;
		}
		case 'label':
			result.value = expect(item, 'value', where, 'string', '');
			if (!result.title) {
				throw new PreferencesConfigError(`${where}.title is required for a label.`);
			}
			break;
	}
	return result;
}

/**
 * Per-platform override: `false` hides the item on that platform, an object is merged into the
 * generated control. `widget` swaps the control type (an iOS specifier such as
 * `PSRadioGroupSpecifier`, or an Android preference class such as `CheckBoxPreference`); every
 * other entry is a raw plist key or XML attribute, and `null` removes one the generator would have
 * written.
 */
function normalizeOverride(override, where, platform) {
	if (override === false) {
		return false;
	}
	if (!override || typeof override !== 'object' || Array.isArray(override)) {
		throw new PreferencesConfigError(`${where} must be false or an object.`);
	}
	const result = {};
	for (const name of Object.keys(override)) {
		const value = override[name];
		if (name === 'widget') {
			const example = platform === 'ios' ? 'PSRadioGroupSpecifier' : 'CheckBoxPreference';
			if (typeof value !== 'string' || !value) {
				throw new PreferencesConfigError(`${where}.widget must be a non-empty string such as "${example}".`);
			}
		} else if (platform === 'ios') {
			if (value !== null && !isPlistValue(value)) {
				throw new PreferencesConfigError(`${where}.${name} must be a string, number, boolean, array of strings or null.`);
			}
		} else {
			if (value !== null && !['string', 'number', 'boolean'].includes(typeof value)) {
				throw new PreferencesConfigError(`${where}.${name} must be a string, number, boolean or null.`);
			}
		}
		result[name] = value;
	}
	return result;
}

function isPlistValue(value) {
	if (typeof value === 'string' || typeof value === 'boolean') {
		return true;
	}
	if (typeof value === 'number') {
		return Number.isFinite(value);
	}
	return Array.isArray(value) && value.every((entry) => typeof entry === 'string');
}

function expect(item, field, where, type, fallback) {
	const value = item[field];
	if (value === undefined) {
		if (fallback === undefined) {
			throw new PreferencesConfigError(`${where}.${field} is required.`);
		}
		return fallback;
	}
	if (typeof value !== type || (type === 'number' && !Number.isFinite(value))) {
		throw new PreferencesConfigError(`${where}.${field} must be a ${type}.`);
	}
	return value;
}

function normalizeOptions(options, where) {
	if (!Array.isArray(options) || !options.length) {
		throw new PreferencesConfigError(`${where}.options must be a non-empty array.`);
	}
	const seen = new Set();
	return options.map((option, index) => {
		let value;
		let title;
		if (typeof option === 'string') {
			value = option;
			title = option;
		} else if (option && typeof option === 'object' && typeof option.value === 'string') {
			value = option.value;
			title = typeof option.title === 'string' ? option.title : option.value;
		} else {
			throw new PreferencesConfigError(`${where}.options[${index}] must be a string or { value, title }.`);
		}
		if (seen.has(value)) {
			throw new PreferencesConfigError(`${where}.options has a duplicate value "${value}".`);
		}
		seen.add(value);
		return { value, title };
	});
}

// Shared helpers ---------------------------------------------------------------------------------

function escapeXml(text) {
	return String(text).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;').replace(/'/g, '&apos;');
}

/** Every item that stores a value, in document order, with nested screens flattened. */
function collectStored(items, result = []) {
	for (const item of items) {
		if (item.type === 'group' || item.type === 'screen') {
			collectStored(item.items, result);
		} else if (item.type !== 'label') {
			result.push(item);
		}
	}
	return result;
}

function collectScreens(items, result = []) {
	for (const item of items) {
		if (item.type === 'screen' && item.ios !== false) {
			result.push(item);
			collectScreens(item.items, result);
		} else if (item.type === 'group') {
			collectScreens(item.items, result);
		}
	}
	return result;
}

// iOS --------------------------------------------------------------------------------------------

const IOS_KEYBOARDS = { default: 'Alphabet', email: 'EmailAddress', number: 'NumberPad', decimal: 'NumbersAndPunctuation', phone: 'NumbersAndPunctuation', url: 'URL' };
const IOS_CAPITALIZATION = { none: 'None', sentences: 'Sentences', words: 'Words', characters: 'AllCharacters' };

function plistValue(value, indent) {
	if (typeof value === 'boolean') {
		return `${indent}<${value}/>`;
	}
	if (typeof value === 'number') {
		return Number.isInteger(value) ? `${indent}<integer>${value}</integer>` : `${indent}<real>${value}</real>`;
	}
	if (Array.isArray(value)) {
		if (!value.length) {
			return `${indent}<array/>`;
		}
		return `${indent}<array>\n${value.map((entry) => plistValue(entry, indent + '\t')).join('\n')}\n${indent}</array>`;
	}
	return `${indent}<string>${escapeXml(value)}</string>`;
}

function plistDict(entries, indent) {
	const lines = [`${indent}<dict>`];
	for (const [key, value] of entries) {
		if (value === undefined) {
			continue;
		}
		lines.push(`${indent}\t<key>${escapeXml(key)}</key>`);
		lines.push(plistValue(value, indent + '\t'));
	}
	lines.push(`${indent}</dict>`);
	return lines.join('\n');
}

/** Maps one item to zero or more iOS specifier dictionaries, honouring `item.ios` overrides. */
function iosSpecifiers(item, warnings) {
	if (item.ios === false) {
		return [];
	}
	const override = item.ios || {};
	if (item.type === 'multilist' && !override.widget) {
		warnings.push(`"${item.key}": iOS Settings has no multi-select control, so this item is left out of Settings.bundle. It still works through the Preferences API.`);
		return [];
	}
	const specifiers = iosBaseSpecifiers(item, warnings);
	if (!specifiers.length || !Object.keys(override).length) {
		return specifiers;
	}
	// Overrides apply to the item's own specifier, which is always the first one emitted.
	specifiers[0] = applyOverrides(specifiers[0], override, 'widget', 'Type');
	return specifiers;
}

/** Merges override entries into an `[name, value]` list: swap the control, then set or remove keys. */
function applyOverrides(entries, override, controlField, controlName) {
	const merged = entries.map(([name, value]) => [name, name === controlName && override[controlField] ? override[controlField] : value]);
	for (const name of Object.keys(override)) {
		if (name === controlField) {
			continue;
		}
		const value = override[name] === null ? undefined : override[name];
		const index = merged.findIndex(([existing]) => existing === name);
		if (index === -1) {
			merged.push([name, value]);
		} else {
			merged[index] = [name, value];
		}
	}
	return merged;
}

function iosBaseSpecifiers(item, warnings) {
	switch (item.type) {
		case 'group':
			return [
				[
					['Type', 'PSGroupSpecifier'],
					['Title', item.title],
					['FooterText', item.summary],
				],
				...item.items.flatMap((child) => iosSpecifiers(child, warnings)),
			];
		case 'screen':
			return [
				[
					['Type', 'PSChildPaneSpecifier'],
					['Title', item.title],
					['File', item.key],
				],
			];
		case 'text':
			return [
				[
					['Type', 'PSTextFieldSpecifier'],
					['Key', item.key],
					['Title', item.title],
					['DefaultValue', item.default],
					['IsSecure', item.secure ? true : undefined],
					['KeyboardType', item.keyboard ? IOS_KEYBOARDS[item.keyboard] : undefined],
					['AutocapitalizationType', item.autocapitalize ? IOS_CAPITALIZATION[item.autocapitalize] : undefined],
					['AutocorrectionType', item.autocorrect === undefined ? undefined : item.autocorrect ? 'Yes' : 'No'],
				],
			];
		case 'toggle':
			return [
				[
					['Type', 'PSToggleSwitchSpecifier'],
					['Key', item.key],
					['Title', item.title],
					['DefaultValue', item.default],
				],
			];
		case 'list':
			return [
				[
					['Type', 'PSMultiValueSpecifier'],
					['Key', item.key],
					['Title', item.title],
					['DefaultValue', item.default],
					['Titles', item.options.map((option) => option.title)],
					['Values', item.options.map((option) => option.value)],
				],
			];
		case 'multilist':
			// Only reached with an explicit `ios.widget`; the data shape matches PSMultiValueSpecifier.
			return [
				[
					['Type', 'PSMultiValueSpecifier'],
					['Key', item.key],
					['Title', item.title],
					['DefaultValue', item.default],
					['Titles', item.options.map((option) => option.title)],
					['Values', item.options.map((option) => option.value)],
				],
			];
		case 'slider':
			return [
				[
					['Type', 'PSSliderSpecifier'],
					['Key', item.key],
					['DefaultValue', item.default],
					['MinimumValue', item.min],
					['MaximumValue', item.max],
				],
			];
		case 'label':
			return [
				[
					['Type', 'PSTitleValueSpecifier'],
					['Key', item.key],
					['Title', item.title],
					['DefaultValue', item.value],
				],
			];
	}
	return [];
}

function renderPlist(items, warnings) {
	const specifiers = items.flatMap((item) => iosSpecifiers(item, warnings));
	const body = specifiers.map((entries) => plistDict(entries, '\t\t')).join('\n');
	return [
		'<?xml version="1.0" encoding="UTF-8"?>',
		'<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">',
		`<!-- ${GENERATED_MARKER} from ${DEFAULT_CONFIG_FILE}. Do not edit; edit ${DEFAULT_CONFIG_FILE} instead. -->`,
		'<plist version="1.0">',
		'<dict>',
		'\t<key>PreferenceSpecifiers</key>',
		'\t<array>',
		body,
		'\t</array>',
		'</dict>',
		'</plist>',
		'',
	].join('\n');
}

function renderIos(config, warnings) {
	const files = new Map();
	files.set('Root.plist', renderPlist(config.items, warnings));
	for (const screen of collectScreens(config.items)) {
		files.set(`${screen.key}.plist`, renderPlist(screen.items, warnings));
	}
	return files;
}

// Android ----------------------------------------------------------------------------------------

function arrayName(item, suffix) {
	return `pref_${item.key.toLowerCase()}_${suffix}`;
}

function androidAttributes(pairs) {
	const present = pairs.filter(([, value]) => value !== undefined);
	// Keep the layout-only attribute last so the meaningful ones read first.
	const ordered = present.filter(([name]) => name !== 'app:iconSpaceReserved').concat(present.filter(([name]) => name === 'app:iconSpaceReserved'));
	return ordered.map(([name, value]) => `${name}="${escapeXml(value)}"`);
}

function androidElement(tag, pairs, children, indent, override) {
	if (override) {
		tag = override.widget || tag;
		pairs = applyOverrides(pairs, override, 'widget', null);
	}
	const attrs = androidAttributes(pairs).map((attribute) => `\n${indent}    ${attribute}`).join('');
	if (!children || !children.length) {
		return `${indent}<${tag}${attrs} />`;
	}
	return `${indent}<${tag}${attrs}>\n\n${children.join('\n\n')}\n${indent}</${tag}>`;
}

function androidPreference(item, indent) {
	if (item.android === false) {
		return undefined;
	}
	const common = [
		['android:key', item.key],
		['android:title', item.title],
		['android:summary', item.summary],
		['app:iconSpaceReserved', 'false'],
	];
	switch (item.type) {
		case 'group':
			return androidElement(
				'PreferenceCategory',
				[
					['android:title', item.title],
					['android:summary', item.summary],
					['app:iconSpaceReserved', 'false'],
				],
				androidChildren(item, indent),
				indent,
				item.android,
			);
		case 'screen':
			return androidElement(
				'PreferenceScreen',
				common,
				androidChildren(item, indent),
				indent,
				item.android,
			);
		case 'text':
			return androidElement(
				'EditTextPreference',
				[
					...common,
					['android:defaultValue', item.default],
					['android:dialogTitle', item.title],
					['app:useSimpleSummaryProvider', item.summary === undefined ? 'true' : undefined],
				],
				null,
				indent,
				item.android,
			);
		case 'toggle':
			return androidElement('SwitchPreferenceCompat', [...common, ['android:defaultValue', String(item.default)]], null, indent, item.android);
		case 'list':
			return androidElement(
				'ListPreference',
				[
					...common,
					['android:entries', `@array/${arrayName(item, 'entries')}`],
					['android:entryValues', `@array/${arrayName(item, 'values')}`],
					['android:defaultValue', item.default],
					['android:dialogTitle', item.title],
					['app:useSimpleSummaryProvider', item.summary === undefined ? 'true' : undefined],
				],
				null,
				indent,
				item.android,
			);
		case 'multilist':
			return androidElement(
				'MultiSelectListPreference',
				[
					...common,
					['android:entries', `@array/${arrayName(item, 'entries')}`],
					['android:entryValues', `@array/${arrayName(item, 'values')}`],
					['android:defaultValue', item.default.length ? `@array/${arrayName(item, 'default')}` : undefined],
					['android:dialogTitle', item.title],
				],
				null,
				indent,
				item.android,
			);
		case 'slider':
			return androidElement(
				'SeekBarPreference',
				[
					...common,
					['android:defaultValue', String(item.default)],
					['app:min', String(item.min)],
					['android:max', String(item.max)],
					['app:seekBarIncrement', item.step === undefined ? undefined : String(item.step)],
					['app:showSeekBarValue', 'true'],
				],
				null,
				indent,
				item.android,
			);
		case 'label':
			return androidElement(
				'Preference',
				[
					['android:key', item.key],
					['android:title', item.title],
					['android:summary', item.value],
					['android:selectable', 'false'],
					['android:persistent', 'false'],
					['app:iconSpaceReserved', 'false'],
				],
				null,
				indent,
				item.android,
			);
	}
	return undefined;
}

function androidChildren(item, indent) {
	return item.items.map((child) => androidPreference(child, indent + '    ')).filter((child) => child !== undefined);
}

function renderAndroidXml(config) {
	return [
		'<?xml version="1.0" encoding="utf-8"?>',
		`<!-- ${GENERATED_MARKER} from ${DEFAULT_CONFIG_FILE}. Do not edit; edit ${DEFAULT_CONFIG_FILE} instead. -->`,
		'<PreferenceScreen xmlns:android="http://schemas.android.com/apk/res/android"',
		'    xmlns:app="http://schemas.android.com/apk/res-auto">',
		'',
		config.items.map((item) => androidPreference(item, '    ')).filter((item) => item !== undefined).join('\n\n'),
		'</PreferenceScreen>',
		'',
	].join('\n');
}

function renderAndroidArrays(config) {
	const arrays = [];
	for (const item of collectStored(config.items)) {
		if (item.type !== 'list' && item.type !== 'multilist') {
			continue;
		}
		arrays.push([arrayName(item, 'entries'), item.options.map((option) => option.title)]);
		arrays.push([arrayName(item, 'values'), item.options.map((option) => option.value)]);
		if (item.type === 'multilist' && item.default.length) {
			arrays.push([arrayName(item, 'default'), item.default]);
		}
	}
	if (!arrays.length) {
		return undefined;
	}
	const body = arrays
		.map(([name, values]) => `    <string-array name="${name}">\n${values.map((value) => `        <item>${escapeXml(value)}</item>`).join('\n')}\n    </string-array>`)
		.join('\n');
	return ['<?xml version="1.0" encoding="utf-8"?>', `<!-- ${GENERATED_MARKER} from ${DEFAULT_CONFIG_FILE}. Do not edit; edit ${DEFAULT_CONFIG_FILE} instead. -->`, '<resources>', body, '</resources>', ''].join('\n');
}

function renderAndroid(config) {
	const files = new Map();
	files.set(`xml/${config.output.androidResource}.xml`, renderAndroidXml(config));
	const arrays = renderAndroidArrays(config);
	if (arrays !== undefined) {
		files.set(`values/${config.output.androidResource}_arrays.xml`, arrays);
	}
	return files;
}

// TypeScript -------------------------------------------------------------------------------------

function tsString(value) {
	return `'${String(value).replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`;
}

function tsType(item) {
	switch (item.type) {
		case 'text':
			return 'string';
		case 'toggle':
			return 'boolean';
		case 'slider':
			return 'number';
		case 'list':
			return item.options.map((option) => tsString(option.value)).join(' | ');
		case 'multilist':
			return 'string[]';
	}
	return 'never';
}

function tsValue(value) {
	if (Array.isArray(value)) {
		return `[${value.map(tsString).join(', ')}]`;
	}
	return typeof value === 'string' ? tsString(value) : String(value);
}

function renderTypeScript(config) {
	const stored = collectStored(config.items);
	const { interfaceName, exportName } = config.output;
	const lines = [
		`// ${GENERATED_MARKER} from ${DEFAULT_CONFIG_FILE}. Do not edit; edit ${DEFAULT_CONFIG_FILE} instead.`,
		"import { Preferences } from 'nativescript-preferences';",
		'',
		`export interface ${interfaceName} {`,
		...stored.map((item) => `\t${item.key}: ${tsType(item)};`),
		'}',
		'',
		`export const ${exportName}Defaults: Readonly<${interfaceName}> = {`,
		...stored.map((item) => `\t${item.key}: ${tsValue(item.default)},`),
		'};',
		'',
		`/** One typed instance for the whole app, backed by the store the OS settings UI edits. */`,
		`export const ${exportName} = new Preferences<${interfaceName}>({ defaults: ${exportName}Defaults });`,
		'',
	];
	return lines.join('\n');
}

// Writing ----------------------------------------------------------------------------------------

function readIfExists(file) {
	try {
		return fs.readFileSync(file, 'utf8');
	} catch (error) {
		return undefined;
	}
}

/**
 * A file that exists without the generated header was written or edited by a person. It is left
 * alone unless `force` is set, so a hand-tuned plist or XML never disappears under a build.
 */
function isHandWritten(existing) {
	return existing !== undefined && !existing.includes(GENERATED_MARKER);
}

function writeIfChanged(file, content, result, force) {
	const existing = readIfExists(file);
	if (existing === content) {
		result.unchanged.push(file);
		return;
	}
	if (isHandWritten(existing) && !force) {
		result.skipped.push(file);
		return;
	}
	fs.mkdirSync(path.dirname(file), { recursive: true });
	fs.writeFileSync(file, content);
	result.written.push(file);
}

/** Removes plists this tool generated earlier that no longer correspond to a screen. */
function pruneStalePlists(bundleDir, keep, result) {
	let entries;
	try {
		entries = fs.readdirSync(bundleDir);
	} catch (error) {
		return;
	}
	for (const entry of entries) {
		if (!entry.endsWith('.plist') || keep.has(entry)) {
			continue;
		}
		const file = path.join(bundleDir, entry);
		let content = '';
		try {
			content = fs.readFileSync(file, 'utf8');
		} catch (error) {
			continue;
		}
		if (content.includes(GENERATED_MARKER)) {
			fs.unlinkSync(file);
			result.removed.push(file);
		}
	}
}

/**
 * Generates every output for `config`.
 *
 * @param config      Result of `loadConfig`.
 * @param options.projectDir       Absolute project root; relative output paths resolve against it.
 * @param options.appResourcesDir  Absolute `App_Resources` path. Defaults to `<projectDir>/App_Resources`.
 * @param options.platforms        Subset of `['ios', 'android']`. Defaults to both.
 * @param options.check            Report what would change without writing anything.
 * @param options.force            Overwrite files that lack the generated header (hand-written or hand-edited).
 *
 * Returns `{ written, unchanged, skipped, removed, warnings }`. `skipped` lists hand-written files
 * that were left alone.
 */
function generate(config, options) {
	const projectDir = path.resolve(options.projectDir || process.cwd());
	const appResourcesDir = options.appResourcesDir ? path.resolve(options.appResourcesDir) : path.join(projectDir, 'App_Resources');
	const platforms = options.platforms || ['ios', 'android'];
	const warnings = [];
	const outputs = new Map();

	const resolveOutput = (configured, fallback) => {
		if (configured === fallback) {
			// Default location: honour a custom App_Resources path from the CLI.
			return path.join(appResourcesDir, path.relative('App_Resources', fallback));
		}
		return path.resolve(projectDir, configured);
	};

	let iosDir;
	if (platforms.includes('ios') && config.output.ios !== false) {
		iosDir = resolveOutput(config.output.ios, DEFAULT_OUTPUT.ios);
		for (const [name, content] of renderIos(config, warnings)) {
			outputs.set(path.join(iosDir, name), content);
		}
	}
	if (platforms.includes('android') && config.output.android !== false) {
		const resDir = resolveOutput(config.output.android, DEFAULT_OUTPUT.android);
		for (const [name, content] of renderAndroid(config)) {
			outputs.set(path.join(resDir, name), content);
		}
	}
	if (config.output.typescript) {
		outputs.set(path.resolve(projectDir, config.output.typescript), renderTypeScript(config));
	}

	const result = { written: [], unchanged: [], skipped: [], removed: [], warnings };
	if (options.check) {
		for (const [file, content] of outputs) {
			const existing = readIfExists(file);
			if (existing === content) {
				result.unchanged.push(file);
			} else if (isHandWritten(existing) && !options.force) {
				result.skipped.push(file);
			} else {
				result.written.push(file);
			}
		}
		return result;
	}
	for (const [file, content] of outputs) {
		writeIfChanged(file, content, result, options.force);
	}
	if (iosDir) {
		pruneStalePlists(iosDir, new Set(Array.from(outputs.keys()).filter((file) => path.dirname(file) === iosDir).map((file) => path.basename(file))), result);
	}
	return result;
}

module.exports = {
	DEFAULT_CONFIG_FILE,
	DEFAULT_OUTPUT,
	GENERATED_MARKER,
	PreferencesConfigError,
	loadConfig,
	normalizeConfig,
	generate,
	renderIos,
	renderAndroid,
	renderAndroidXml,
	renderAndroidArrays,
	renderTypeScript,
	renderPlist,
};
